FROM node:20-alpine

WORKDIR /app

# Install development dependencies
COPY package*.json ./
RUN npm install

# No need to copy source files as they will be mounted as a volume

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
